# Generated from silx 3.1.2's `silx.io.url.DataUrl` by test/generate_silx_cases.py, which runs
# each string through it and records what it reports. Do not edit by hand: regenerate instead.
# Fields: text, valid, absolute, scheme, file_path, data_path, data_slice, invalid_reason.
const SILX_PARSED_URLS = [
    ("fabio:///data/image.edf?slice=2", true, true, "fabio", "/data/image.edf", nothing, (2,), nothing),
    ("fabio:///C:/data/image.edf?slice=2", true, true, "fabio", "C:/data/image.edf", nothing, (2,), nothing),
    ("silx:///data/image.h5?path=/data/dataset&slice=1,5", true, true, "silx", "/data/image.h5", "/data/dataset", (1, 5), nothing),
    ("silx:///data/image.h5::path=/data/dataset&slice=1,5", true, true, "silx", "/data/image.h5", "/data/dataset", (1, 5), nothing),
    ("silx:///data/image.edf?/scan_0/detector/data", true, true, "silx", "/data/image.edf", "/scan_0/detector/data", nothing, nothing),
    ("silx:///C:/data/image.h5?/scan_0/detector/data", true, true, "silx", "C:/data/image.h5", "/scan_0/detector/data", nothing, nothing),
    ("silx:./image.h5", true, false, "silx", "./image.h5", nothing, nothing, nothing),
    ("fabio:./image.edf", true, false, "fabio", "./image.edf", nothing, nothing, nothing),
    ("silx:image.h5", true, false, "silx", "image.h5", nothing, nothing, nothing),
    ("fabio:image.edf", true, false, "fabio", "image.edf", nothing, nothing, nothing),
    ("image.edf", true, false, nothing, "image.edf", nothing, nothing, nothing),
    ("./foo/bar/image.edf", true, false, nothing, "./foo/bar/image.edf", nothing, nothing, nothing),
    ("foo/bar/image.edf", true, false, nothing, "foo/bar/image.edf", nothing, nothing, nothing),
    ("/data/image.edf", true, true, nothing, "/data/image.edf", nothing, nothing, nothing),
    ("C:/data/image.edf", true, true, nothing, "C:/data/image.edf", nothing, nothing, nothing),
    ("/foo/foobar.h5?/foo/bar", true, true, nothing, "/foo/foobar.h5", "/foo/bar", nothing, nothing),
    ("C:/foo/foobar.h5?path=/foo/bar&slice=5,1", true, true, nothing, "C:/foo/foobar.h5", "/foo/bar", (5, 1), nothing),
    ("silx:/foo/foobar.h5?path=/foo/bar&slice=5,1", true, true, "silx", "/foo/foobar.h5", "/foo/bar", (5, 1), nothing),
    ("silx:C:/foo/foobar.h5?path=/foo/bar&slice=5,1", true, true, "silx", "C:/foo/foobar.h5", "/foo/bar", (5, 1), nothing),
    ("", false, false, nothing, "", nothing, nothing, "Invalid file path"),
    ("foo:/foo/foobar.h5?path=/foo/bar&slice=5,1", false, true, "foo", "/foo/foobar.h5", "/foo/bar", (5, 1), "Invalid scheme. It can only be fabio, silx, http, https."),
    ("/a.h5?path=/b&slice=5,1", true, true, nothing, "/a.h5", "/b", (5, 1), nothing),
    ("/a.h5?path=/b&slice=2:5", true, true, nothing, "/a.h5", "/b", (SliceRange(2, 5, nothing),), nothing),
    ("/a.h5?path=/b&slice=::2", true, true, nothing, "/a.h5", "/b", (SliceRange(nothing, nothing, 2),), nothing),
    ("/a.h5?path=/b&slice=...", true, true, nothing, "/a.h5", "/b", (SliceEllipsis(),), nothing),
    ("/a.h5?path=/b&slice=:", true, true, nothing, "/a.h5", "/b", (SliceRange(nothing, nothing, nothing),), nothing),
    ("/a.h5?path=/b&slice=5,,1", false, true, nothing, "/a.h5", "/b", nothing, "Invalid slice"),
    ("/a.h5?path=/b&slice=", false, true, nothing, "/a.h5", "/b", nothing, "Invalid slice"),
    ("http://hsds-server.tld/home/file", true, false, "http", "hsds-server.tld/home/file", nothing, nothing, nothing),
    ("http://hsds-server.tld:8080/home/file", true, false, "http", "hsds-server.tld:8080/home/file", nothing, nothing, nothing),
    ("http://hsds-server.tld/home/file?/foo/bar", true, false, "http", "hsds-server.tld/home/file", "/foo/bar", nothing, nothing),
    ("silx://my_file.hdf5?path=/path/to/data&slice=not_a_slice", false, false, "silx", "my_file.hdf5", "/path/to/data", nothing, "Invalid slice"),
    ("/data/scan.h5::/entry/data", true, true, nothing, "/data/scan.h5", "/entry/data", nothing, nothing),
    ("fabio:/users/foo/image.edf::[0]", false, true, "fabio", "/users/foo/image.edf", "[0]", nothing, "fabio URLs cannot have a data path"),
    ("silx:/a.h5::/b/c", true, true, "silx", "/a.h5", "/b/c", nothing, nothing),
    ("/a.h5?path=/b&slice=-1,::-1,1:-2:3", true, true, nothing, "/a.h5", "/b", (-1, SliceRange(nothing, nothing, -1), SliceRange(1, -2, 3)), nothing),
    ("/a.h5?slice=3", true, true, nothing, "/a.h5", nothing, (3,), nothing),
    ("silx:/a.h5?slice=3", false, true, "silx", "/a.h5", nothing, (3,), "silx URLs cannot have a slice with no data path"),
    ("fabio:/a.edf?path=/x", false, true, "fabio", "/a.edf", "/x", nothing, "fabio URLs cannot have a data path"),
    ("fabio:/a.edf?slice=1,2", true, true, "fabio", "/a.edf", nothing, (1, 2), nothing),
    ("/a.h5?path=/b%20c&slice=+2", true, true, nothing, "/a.h5", "/b c", (2,), nothing),
    ("/a.h5?path=/b+c", true, true, nothing, "/a.h5", "/b c", nothing, nothing),
    ("/a.h5?path=/x&path=/y", true, true, nothing, "/a.h5", "/y", nothing, nothing),
    ("/a.h5?path=/x&foo=1", true, true, nothing, "/a.h5", "/x", nothing, nothing),
    ("SILX:/a.h5?/b", true, true, "silx", "/a.h5", "/b", nothing, nothing),
    ("d:/a.edf", true, true, nothing, "d:/a.edf", nothing, nothing, nothing),
    ("file:/a.edf", false, true, "file", "/a.edf", nothing, nothing, "Invalid scheme. It can only be fabio, silx, http, https."),
    ("relative.h5::/entry", true, false, nothing, "relative.h5", "/entry", nothing, nothing),
    ("/a.h5?slice= 3 ,1_0", true, true, nothing, "/a.h5", nothing, (3, 10), nothing),
    ("/a.h5?path=/b&slice=1:2:3:4", true, true, nothing, "/a.h5", "/b", (SliceRange(1, 2, 3),), nothing),
    ("/a.h5?path=/b&slice=1:x", false, true, nothing, "/a.h5", "/b", nothing, "Invalid slice"),
    ("silx:///a.h5?path=/b&slice=..., 0", true, true, "silx", "/a.h5", "/b", (SliceEllipsis(), 0), nothing),
    ("/a.h5??/b", true, true, nothing, "/a.h5", "?/b", nothing, nothing),
    ("/a b.h5::/c d", true, true, nothing, "/a b.h5", "/c d", nothing, nothing),
    ("//host?x", false, false, nothing, "", "x", nothing, "Invalid file path"),
    ("//server/share/x.h5::/e", true, true, nothing, "//server/share/x.h5", "/e", nothing, nothing),
    ("/\u00e9:x.h5?/a", true, true, nothing, "/\u00e9:x.h5", "/a", nothing, nothing),
    ("silx:///\u00e9/x.h5?/b", true, true, "silx", "/\u00e9/x.h5", "/b", nothing, nothing),
    ("\u00e9.h5::/d", true, false, nothing, "\u00e9.h5", "/d", nothing, nothing),
    ("silx:\u00e9:/x", true, true, "silx", "\u00e9:/x", nothing, nothing, nothing),
    ("?/b", false, false, nothing, "", "/b", nothing, "Invalid file path"),
    ("::/b", false, false, nothing, "", "/b", nothing, "Invalid file path"),
    ("C:/x::/y", true, true, nothing, "C:/x", "/y", nothing, nothing),
]

# DataUrl built from parts, and the text silx's `DataUrl.path()` gives for it.
# Fields: file_path, data_path, data_slice, scheme, path, valid, invalid_reason.
const SILX_BUILT_URLS = [
    ("./foo.h5", "/", (5, 1), "silx", "silx://./foo.h5?path=/&slice=5,1", true, nothing),
    ("/foo.h5", "/", (5, 1), "silx", "silx:///foo.h5?path=/&slice=5,1", true, nothing),
    ("C:/foo.h5", "/", (5, 1), "silx", "silx:///C:/foo.h5?path=/&slice=5,1", true, nothing),
    ("/foo.h5", "/", (5, 1, SliceEllipsis(), SliceRange(nothing, nothing, nothing)), "silx", "silx:///foo.h5?path=/&slice=5,1,...,:", true, nothing),
    ("/foo.h5", nothing, (1,), "silx", "silx:///foo.h5?slice=1", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (1,), "silx", "silx:///foo.h5?slice=1", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (SliceRange(nothing, nothing, nothing),), "silx", "silx:///foo.h5?slice=:", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (SliceRange(1, nothing, nothing),), "silx", "silx:///foo.h5?slice=1:", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (SliceRange(nothing, -2, nothing),), "silx", "silx:///foo.h5?slice=:-2", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (SliceRange(1, nothing, 3),), "silx", "silx:///foo.h5?slice=1::3", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (SliceRange(nothing, 2, 3),), "silx", "silx:///foo.h5?slice=:2:3", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (SliceRange(nothing, nothing, 3),), "silx", "silx:///foo.h5?slice=::3", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (SliceRange(1, 2, 3),), "silx", "silx:///foo.h5?slice=1:2:3", false, "silx URLs cannot have a slice with no data path"),
    ("/foo.h5", nothing, (1, SliceRange(1, 2, nothing)), "silx", "silx:///foo.h5?slice=1,1:2", false, "silx URLs cannot have a slice with no data path"),
    ("rel.edf", nothing, (2,), "fabio", "fabio://rel.edf?slice=2", true, nothing),
    ("/a.h5", "/entry", nothing, nothing, "/a.h5?/entry", true, nothing),
    ("/a.h5", nothing, nothing, nothing, "/a.h5", true, nothing),
    ("/a.h5", "/entry", (0,), nothing, "/a.h5?path=/entry&slice=0", true, nothing),
]
